name: RandomCoords
main: com.jolbol1.RandomCoordinates.RandomCoords
#version: ${project.version}-${REPO}-${BRANCH}-b${BUILD_NUMBER}-${buildTimestamp}
version: 2.3.0
website: http://bukkit.org
author: Jolbol1
authors: [PHENOMICAL]
api-version: 1.14
softdepend: [Factions, MassiveCore, WorldEdit, WorldBorder, Vault, WorldGuard, Essentials, Towny, Residence, RedProtect, Kingdoms, GriefPrevention, PlotSquared]
description: >
             Get away quick with a random coordinate.
commands:
  rc:
    description: Teleport to a random coordinate.
    usage: /<command>
    aliases: [randomcoord, randomcoords, randomcoordinates, wild, rtp]